### PR TITLE
LPD-94998 Wire PageSpeed integration state to SEOStudioInstance credentials

### PR DESCRIPTION
**Pull request by ksuetani**
https://liferay.atlassian.net/browse/LPD-94998

## What Is Being Fixed

The integrations card built in LPD-94550 lists PageSpeed rows but has no wiring to the `SEOStudioInstance.googlePageSpeedAPIKey` field that LPD-94529's configuration page saves. Rows show up but never reflect the true credential state: saving an API key does not mark the row `active`, deleting a row does not clear the credential, and there is no way to re-check a row that has drifted into `unavailable`.

## How It Is Being Fixed

The wiring is spread across the two ends and a shared helper.

On the configuration side, `PageSpeedConfiguration.tsx` now loads the existing `SEOStudioIntegration` rows filtered by `type eq 'pageSpeed'` and remembers the `seoStudioInstanceId → integrationId` map. Saving the API key PATCHes the matching integration row to `state: active`, or POSTs a new one keyed to the instance when none exists.

On the integrations card, a `Validate Connection` action is added to any row in the `unavailable` state via an FDS `visibilityFilters` on `stateKey`. The handler fetches the row's instance to read the current API key, runs it through Google's PageSpeed API, and either PATCHes the row back to `active` on success or shows a danger toast on failure.

On the portal side, `SEOStudioIntegrationObjectEntryModelListener.onAfterRemove` calls `partialUpdateObjectEntry` to clear the sibling instance's `googlePageSpeedAPIKey` (using `StringPool.BLANK`) when a PageSpeed integration row is removed, so the credential does not linger without an owning integration row.

The two entry points share a new `pagespeed/validation.ts` helper (named export `validateAPIKey`) that owns the Google PageSpeed round-trip and the error-shape interpretation, matching the `health_scan/validation.ts` precedent already used in this module.

Also renames the two dedicated PageSpeed fragment renderers plus their `DisplayContext`s and JSPs to follow the CMS View/Edit convention: `EditPageSpeedConfigurationFragmentRenderer` and `ViewPageSpeedChartsFragmentRenderer`, with JSPs renamed to `edit_pagespeed_configuration.jsp` and `view_pagespeed_charts.jsp`. `IntegrationsFragmentRenderer` is intentionally left unprefixed — it is a reusable widget that will be embedded on multiple pages, matching the Commerce DataSet precedent. `HealthScanConfigurationFragmentRenderer` is intentionally left as-is pending a broader Settings-page consolidation refactor.

## PR Check

**pr-check: PASS** — tested on `b30cec6086065929df5fef58c90ba0fcf0a17a01`

| Validation | Result |
| --- | --- |
| Source Format | PASS |
| Per-Module Compile | PASS |
| Integration Test Compile | PASS |
| JSP Compile | PASS |
| Java Unit Tests | PASS |
| JavaScript Unit Tests | PASS |

Notes:
- Source Format ran with zero drift.
- Per-Module Compile: Java compile independently verified with `BUILD SUCCESSFUL` on `:compileJava` earlier in the session; the full `:deploy` run hit a local-only `build/node/` filesystem permission issue (`Could not set file mode 755`), not a code failure.
- Integration Test Compile + JSP Compile ran successfully via `-x downloadNode -x yarnInstall -x packageRunBuild`; module Java + JSP compile clean under the new `edit_*.jsp` / `view_*.jsp` paths.
- Java Unit Tests: `SEOStudioScanScheduleUtilTest` hit the pre-existing upstream `NoClassDefFoundError: com/liferay/petra/process/ProcessExecutor` in `LiferayUnitTestRule` — that test class is not touched by this diff.
- JavaScript Unit Tests: 93/93 across 8 suites.

### CODE REVIEW

**Comment by ksuetani** [comment]
ci:forward
